/*global systemDictionary:true */
'use strict';

systemDictionary = {
    'Cancel': {                                      'en': 'cancel',                                          'de': 'abbrechen',                                       'ru': 'отменить',                                        'pt': 'cancelar',                                        'nl': 'annuleren',                                       'fr': 'Annuler',                                         'it': 'Annulla',                                         'es': 'cancelar',                                        'pl': 'Anuluj',                                          'zh-cn': '取消'},
    'Name': {                                        'en': 'name',                                            'de': 'Name',                                            'ru': 'название',                                        'pt': 'nome',                                            'nl': 'naam',                                            'fr': 'prénom',                                          'it': 'nome',                                            'es': 'nombre',                                          'pl': 'Nazwa',                                           'zh-cn': '名称'},
    'Object-ID': {                                   'en': 'object ID',                                       'de': 'Objekt ID',                                       'ru': 'идентификатор объекта',                           'pt': 'ID do objeto',                                    'nl': 'object ID',                                       'fr': "ID d'objet",                                      'it': 'ID oggetto',                                      'es': 'ID de objeto',                                    'pl': 'identyfikator obiektu',                           'zh-cn': '对象ID'},
    'Password': {                                    'en': 'password',                                        'de': 'Passwort',                                        'ru': 'пароль',                                          'pt': 'senha',                                           'nl': 'wachtwoord',                                      'fr': 'mot de passe',                                    'it': "parola d'ordine",                                 'es': 'contraseña',                                      'pl': 'hasło',                                           'zh-cn': '密码'},
    'Select': {                                      'en': 'select',                                          'de': 'wählen',                                          'ru': 'Выбрать',                                         'pt': 'selecionar',                                      'nl': 'kiezen',                                          'fr': 'sélectionner',                                    'it': 'selezionare',                                     'es': 'seleccionar',                                     'pl': 'Wybierz',                                         'zh-cn': '选择'},
    'active': {                                      'en': 'active',                                          'de': 'aktiv',                                           'ru': 'активный',                                        'pt': 'ativo',                                           'nl': 'actief',                                          'fr': 'actif',                                           'it': 'attivo',                                          'es': 'activo',                                          'pl': 'aktywny',                                         'zh-cn': '活性'},
    'alarm': {                                       'en': 'alarm circuit',                                   'de': 'Alarmkreis',                                      'ru': 'цепь сигнализации',                               'pt': 'circuito de alarme',                              'nl': 'alarmcircuit',                                    'fr': "circuit d'alarme",                                'it': 'circuito di allarme',                             'es': 'circuito de alarma',                              'pl': 'obwód alarmowy',                                  'zh-cn': '报警电路'},
    'alarm_Chips': {                                 'en': 'States for alarm circuit',                        'de': 'Zustände für den Alarmkreis',                     'ru': 'Состояния для аварийной цепи',                    'pt': 'Estados para circuito de alarme',                 'nl': 'Staten voor alarmcircuit',                        'fr': "États pour le circuit d'alarme",                  'it': 'Stati per circuito di allarme',                   'es': 'Estados para circuito de alarma',                 'pl': 'Stany dla obwodu alarmowego',                     'zh-cn': '报警电路的状态'},
    'alarm_flash': {                                 'en': 'flash light frequenz at burgle',
        'de': 'Blitzlichtfrequenz bei Einbruch',
        'ru': 'частота вспышки света на Burgle',
        'pt': 'luz do flash frequenz em burgle',
        'nl': 'flitslicht frequenz bij burgle',
        'fr': 'flash de fréquence à burgle',
        'it': 'luce flash frequenz a burgle',
        'es': 'Frecuencia de luz de flash en burgle',
        'pl': 'flash light frequency at burgle',
        'zh-cn': '防盗闪光灯'},
    'circuits': {                                    'en': 'Circuits for sharp, sharpf inside and notifications', 'de': 'Kreise für scharf, scharf innen und Benachrichtigungen', 'ru': 'Схемы для острых, острых внутри и уведомлений',   'pt': 'Circuitos para afiado, afiado por dentro e notificações', 'nl': 'Circuits voor scherpe, scherpe binnenkant en meldingen', 'fr': 'Circuits pour sharp, sharpf inside et notifications', 'it': "Circuiti per nitidi, nitidi all'interno e notifiche", 'es': 'Circuitos para sharp, sharpf dentro y notificaciones', 'pl': 'Obwody do ostrych, ostrych wewnątrz i powiadomień', 'zh-cn': '尖锐，尖锐的内部电路和通知'},
    'delay': {
        'en': 'silent alarm',
        'de': 'Stiller Alarm',
        'ru': 'тихая тревога',
        'pt': 'alarme silencioso',
        'nl': 'stil alarm',
        'fr': 'alarme silencieuse',
        'it': 'allarme silenzioso',
        'es': 'alarma silenciosa',
        'pl': 'cichy alarm',
        'zh-cn': '静音警报'},
    'delay_inside': {
        'en': 'silent alarm sharp inside',
        'de': 'Stiller Alarm scharf innen',
        'ru': 'тихая тревога острая внутри',
        'pt': 'alarme silencioso afiado por dentro',
        'nl': 'stil alarm scherp van binnen',
        'fr': "alarme silencieuse à l'intérieur",
        'it': "allarme silenzioso acuto all'interno",
        'es': 'alarma silenciosa aguda en el interior',
        'pl': 'cichy alarm ostry w środku',
        'zh-cn': '静音报警尖锐内部'},
    'speech_delay': {
        'en': 'delay (sec)',
        'de': 'Verzögerung (Sek.)',
        'ru': 'задержка (сек)',
        'pt': 'atraso (s)',
        'nl': 'vertraging (sec)',
        'fr': 'délai (sec)',
        'it': 'ritardo (sec)',
        'es': 'retraso (seg)',
        'pl': 'opóźnienie (sek)',
        'zh-cn': '延迟（秒）'
    },
    'disabled': {                                    'en': 'disabled',                                        'de': 'deaktiviert',                                     'ru': 'отключен',                                        'pt': 'Desativado',                                      'nl': 'invalide',                                        'fr': 'désactivée',                                      'it': 'Disabilitato',                                    'es': 'discapacitado',                                   'pl': 'wyłączone',                                       'zh-cn': '残'},
    'donat': {'en': "I'm not a professional developer and this is a private project, the development takes place in my spare time, if you want to support this you can thank me with a donation under PayPal. You are also welcome to send me feature requests for future versions of the adapter.",
        'de': 'Ich bin kein professioneller Entwickler und dies ist ein privates Projekt, die Entwicklung findet in meiner Freizeit statt, wenn Sie dies unterstützen möchten, können Sie sich mit einer Spende unter PayPal bei mir bedanken. Sie können mir auch gerne Funktionsanfragen für zukünftige Versionen des Adapters senden.',
        'ru': 'Я не профессиональный разработчик, и это частный проект, разработка происходит в свободное время, если вы хотите поддержать это, вы можете отблагодарить меня пожертвованием через PayPal. Вы также можете присылать мне запросы функций для будущих версий адаптера.',
        'pt': 'Eu não sou um desenvolvedor profissional e este é um projeto privado, o desenvolvimento ocorre no meu tempo livre, se você quiser apoiar isso, pode me agradecer com uma doação no PayPal. Você também pode me enviar solicitações de recursos para versões futuras do adaptador.',
        'nl': 'Ik ben geen professionele ontwikkelaar en dit is een privé project, de ontwikkeling vindt plaats in mijn vrije tijd, als je dit wilt steunen kun je me bedanken met een donatie onder PayPal. U bent ook welkom om mij functieverzoeken te sturen voor toekomstige versies van de adapter.',
        'fr': "Je ne suis pas un développeur professionnel et c'est un projet privé, le développement a lieu sur mon temps libre, si vous voulez soutenir cela vous pouvez me remercier avec un don sous PayPal. Vous pouvez également m'envoyer des demandes de fonctionnalités pour les futures versions de l'adaptateur.",
        'it': "Non sono uno sviluppatore professionista e questo è un progetto privato, lo sviluppo avviene nel mio tempo libero, se vuoi supportarlo puoi ringraziarmi con una donazione sotto PayPal. Puoi anche inviarmi richieste di funzionalità per versioni future dell'adattatore.",
        'es': 'No soy un desarrollador profesional y este es un proyecto privado, el desarrollo se lleva a cabo en mi tiempo libre, si quieres apoyar esto puedes agradecerme con una donación a través de PayPal. También puede enviarme solicitudes de funciones para futuras versiones del adaptador.',
        'pl': 'Nie jestem profesjonalnym programistą i jest to projekt prywatny, rozwój odbywa się w wolnym czasie, jeśli chcesz to wesprzeć, możesz mi podziękować darowizną w systemie PayPal. Zapraszam również do przesyłania mi próśb o funkcje dla przyszłych wersji adaptera.',
        'zh-cn': '我不是专业开发人员，这是一个私人项目，开发是在我的业余时间进行的，如果你想支持这个，你可以通过 PayPal 捐款来感谢我。也欢迎您向我发送有关适配器未来版本的功能请求。'},
    'general': {                                     'en': 'Main settings',                                   'de': 'Haupteinstellungen',                              'ru': 'Основные параметры',                              'pt': 'Configurações principais',                        'nl': 'Belangrijkste instellingen',                      'fr': 'Réglages principaux',                             'it': 'Impostazioni principali',                         'es': 'Ajustes principales',                             'pl': 'Ustawienia główne',                               'zh-cn': '主要设置'},
    'general_settings': { 'en': 'general settings',
        'de': 'Allgemeine Einstellungen',
        'ru': 'общие настройки',
        'pt': 'Configurações Gerais',
        'nl': 'Algemene instellingen',
        'fr': 'réglages généraux',
        'it': 'impostazioni generali',
        'es': 'Configuración general',
        'pl': 'Ustawienia główne',
        'zh-cn': '常规设置'},
    'important': {                                   'en': 'Important! Do not create loops.',                 'de': 'Wichtig! Erstellen Sie keine Schleifen.',         'ru': 'Важный! Не создавайте петли.',                    'pt': 'Importante! Não crie loops.',                     'nl': 'Belangrijk! Maak geen lussen.',                   'fr': 'Important! Ne créez pas de boucles.',             'it': 'Importante! Non creare loop.',                    'es': '¡Importante! No cree bucles.',                    'pl': 'Ważny! Nie twórz pętli.',                         'zh-cn': '重要！不要创建循环。'},
    'input': {                                   'en': 'Input shortcuts',                                 'de': 'Eingabeverknüpfungen',                            'ru': 'Входные ярлыки',                                  'pt': 'Atalhos de entrada',                              'nl': 'Sneltoetsen invoeren',                            'fr': "Raccourcis d'entrée",                             'it': 'Scorciatoie di input',                            'es': 'Atajos de entrada',                               'pl': 'Skróty wprowadzania',                             'zh-cn': '输入快捷键'},
    'info_words': {                                  'en': 'You can edit the notifications at words tab',     'de': 'Texte der Benachrichtigungen können auf der Registerkarte Texte bearbeitet werden', 'ru': 'Вы можете редактировать уведомления на вкладке слов', 'pt': 'Você pode editar as notificações na guia palavras', 'nl': 'Je kunt de meldingen bewerken op het tabblad Woorden', 'fr': "Vous pouvez modifier les notifications dans l'onglet mots", 'it': 'Puoi modificare le notifiche nella scheda parole', 'es': 'Puedes editar las notificaciones en la pestaña de palabras', 'pl': 'Możesz edytować powiadomienia na karcie słów',    'zh-cn': '您可以在单词选项卡上编辑通知'},
    'input_logs': {                                       'en': 'You can edit the notifications at words tab',     'de': 'Texte der Benachrichtigungen können auf der Registerkarte Texte bearbeitet werden', 'ru': 'Вы можете редактировать уведомления на вкладке слов', 'pt': 'Você pode editar as notificações na guia palavras', 'nl': 'Je kunt de meldingen bewerken op het tabblad Woorden', 'fr': "Vous pouvez modifier les notifications dans l'onglet mots", 'it': 'Puoi modificare le notifiche nella scheda parole', 'es': 'Puedes editar las notificaciones en la pestaña de palabras', 'pl': 'Możesz edytować powiadomienia na karcie słów',    'zh-cn': '您可以在单词选项卡上编辑通知'},
    'inside': {                                      'en': 'Sharp inside',                                    'de': 'Scharf innen',                                    'ru': 'Острый внутри',                                   'pt': 'Afiado por dentro',                               'nl': 'Scherp van binnen',                               'fr': "Vif à l'intérieur",                               'it': 'Sharp dentro',                                    'es': 'Afilado por dentro',                              'pl': 'Ostro w środku',                                  'zh-cn': '里面锋利'},
    'leave': {       'en': 'leave',
        'de': 'verlassen',
        'ru': 'оставлять',
        'pt': 'sair',
        'nl': 'vertrekken',
        'fr': 'laisser',
        'it': 'partire',
        'es': 'dejar',
        'pl': 'Zostawić',
        'zh-cn': '离开'                              },
    'log_act': {                                     'en': 'Activated',                                       'de': 'Aktiviert',                                       'ru': 'активированная',                                  'pt': 'ativado',                                         'nl': 'Geactiveerd',                                     'fr': 'Activé',                                          'it': 'attivato',                                        'es': 'Activado',                                        'pl': 'Aktywowany',                                      'zh-cn': '活性'},
    'log_act_not': {                                 'en': 'Can not activate',                                'de': 'Kann nicht aktiviert werden',                     'ru': 'Не может активировать',                           'pt': 'Não é possível ativar',                           'nl': 'Kan niet activeren',                              'fr': "Impossible d'activer",                            'it': 'Impossibile attivare',                            'es': 'No se puede activar',                             'pl': 'Nie można aktywować',                             'zh-cn': '无法激活'},
    'log_act_warn': {                                'en': 'Activated with warnings',                         'de': 'Mit Warnungen aktiviert',                         'ru': 'Активируется с предупреждениями',                 'pt': 'Ativado com avisos',                              'nl': 'Geactiveerd met waarschuwingen',                  'fr': 'Activé avec des avertissements',                  'it': 'Attivato con avvisi',                             'es': 'Activado con advertencias',                       'pl': 'Aktywowany z ostrzeżeniami',                      'zh-cn': '警告激活'},
    'log_act_warn_circuit': {                        'en': 'Warn circuit notify at activation',               'de': 'Warnkreis meldet Warnungen bei Aktivierung',      'ru': 'Предупреждать об уведомлении цепи при активации', 'pt': 'Avisar circuito notificar na ativação',           'nl': 'Waarschuw circuit bij activering',                'fr': "Avertir le circuit d'avertir à l'activation",     'it': "Avvisa circuito avvisa all'attivazione",          'es': 'Advertir circuito notificar en la activación',    'pl': 'Ostrzegaj obwód powiadomienie przy aktywacji',    'zh-cn': '警告电路在激活时通知'},
    'log_act_notice':{'en': 'Notice at activation with delay',
        'de': 'Hinweis bei Aktivierung mit Verzögerung',
        'ru': 'Уведомление при активации с задержкой',
        'pt': 'Aviso na ativação com atraso',
        'nl': 'Melding bij activering met vertraging',
        'fr': "Avis à l'activation avec délai",
        'it': "Avviso all'attivazione con ritardo",
        'es': 'Aviso en la activación con retraso',
        'pl': 'Uwaga przy aktywacji z opóźnieniem',
        'zh-cn': '激活延迟通知'},
    'log_burgle': {                                  'en': 'Burgle',                                          'de': 'Einbruch',                                        'ru': 'быть взломщиком',                                 'pt': 'Burgle',                                          'nl': 'Burgle',                                          'fr': 'Cambrioler',                                      'it': 'Scassinare',                                      'es': 'Robar con fractura',                              'pl': 'Włamać się',                                      'zh-cn': 'gle'},
    'log_deact': {                                   'en': 'Deactivated',                                     'de': 'Deaktiviert',                                     'ru': 'ММГ',                                             'pt': 'Desativado',                                      'nl': 'Gedeactiveerd',                                   'fr': 'Désactivée',                                      'it': 'Disattivato',                                     'es': 'Desactivado',                                     'pl': 'Dezaktywowano',                                   'zh-cn': '已停用'},
    'log_night': {                                   'en': 'Changes during night rest',                       'de': 'Veränderungen während der Nachtruhe',             'ru': 'Изменения во время ночного отдыха',               'pt': 'Mudanças durante o descanso noturno',             'nl': 'Veranderingen tijdens nachtrust',                 'fr': 'Changements pendant le repos nocturne',           'it': 'Cambiamenti durante il riposo notturno',          'es': 'Cambios durante el descanso nocturno.',           'pl': 'Zmiany podczas nocnego odpoczynku',               'zh-cn': '夜间休息时的变化'},
    'log_nights_b_w': {                              'en': 'Night rest begins with warnings',                 'de': 'Nachtruhe beginnt mit Warnungen',                 'ru': 'Начинается ночной отдых',                         'pt': 'O resto da noite começa',                         'nl': 'Nachtrust begint',                                'fr': 'Le repos nocturne commence',                      'it': 'Inizia il riposo notturno',                       'es': 'Comienza el descanso nocturno',                   'pl': 'Rozpoczyna się nocny odpoczynek',                 'zh-cn': '晚上休息开始'},
    'log_panic': {                                   'en': 'Burgle by panic button',                          'de': 'Einbruch durch Panikknopf',                       'ru': 'Burgle от кнопки паники',                         'pt': 'Burgle pelo botão de pânico',                     'nl': 'Inbraak door paniekknop',                         'fr': 'Burgle par bouton panique',                       'it': 'Burgle con pulsante antipanico',                  'es': 'Burgle por botón de pánico',                      'pl': 'Przycisk napadowy Burgle',                        'zh-cn': '通过紧急按钮叫'},
    'log_pass': {                                    'en': 'Wrong password',                                  'de': 'Falsches Passwort',                               'ru': 'Неправильный пароль',                             'pt': 'Senha incorreta',                                 'nl': 'Verkeerd wachtwoord',                             'fr': 'Mauvais mot de passe',                            'it': 'Password errata',                                 'es': 'Contraseña incorrecta',                           'pl': 'Złe hasło',                                       'zh-cn': '密码错误'},
    'log_sleep_b': {                                 'en': 'Night rest begins',                               'de': 'Nachtruhe beginnt',                               'ru': 'Начинается ночной отдых',                         'pt': 'O resto da noite começa',                         'nl': 'Nachtrust begint',                                'fr': 'Le repos nocturne commence',                      'it': 'Inizia il riposo notturno',                       'es': 'Comienza el descanso nocturno',                   'pl': 'Rozpoczyna się nocny odpoczynek',                 'zh-cn': '晚上休息开始'},
    'log_sleep_e': {                                 'en': 'Night rest ends',                                 'de': 'Nachtruhe endet',                                 'ru': 'Ночной отдых заканчивается',                      'pt': 'O resto da noite termina',                        'nl': 'De nachtrust eindigt',                            'fr': 'Fin du repos nocturne',                           'it': 'Il riposo notturno finisce',                      'es': 'El descanso nocturno termina',                    'pl': 'Nocny odpoczynek się kończy',                     'zh-cn': '晚上休息结束'},
    'log_warn': {                                    'en': 'Changes',                                         'de': 'Veränderungen',                                   'ru': 'изменения',                                       'pt': 'Alterar',                                         'nl': 'Veranderingen',                                   'fr': 'Changements',                                     'it': 'I cambiamenti',                                   'es': 'Cambios',                                         'pl': 'Zmiany',                                          'zh-cn': '变化'},
    'log_warn_act': {                                'en': 'Sharp inside activated',                          'de': 'Scharf innen aktiviert',                          'ru': 'Острый внутри активирован',                       'pt': 'Nítido por dentro ativado',                       'nl': 'Scherpe binnenkant geactiveerd',                  'fr': "Sharp à l'intérieur activé",                      'it': 'Sharp interno attivato',                          'es': 'Sharp dentro activado',                           'pl': 'Ostre wnętrze aktywowane',                        'zh-cn': '尖锐的内部已激活'},
    'log_warn_b_w': {                                'en': 'sharp inside activated with warnings',
        'de': 'Scharf innen mit Warnungen aktiviert',
        'ru': 'острый внутри активирован с предупреждениями',
        'pt': 'interior afiado ativado com avisos',
        'nl': 'scherpe binnenkant geactiveerd met waarschuwingen',
        'fr': 'intérieur pointu activé avec avertissements',
        'it': 'interno nitido attivato con avvisi',
        'es': 'agudo interior activado con advertencias',
        'pl': 'ostry wewnątrz aktywowany ostrzeżeniami',
        'zh-cn': '尖锐的内部被警告激活'},
    'log_warn_deact': {                              'en': 'Sharp inside deactivated',                        'de': 'Scharf innen deaktiviert',                        'ru': 'Острый внутри деактивирован',                     'pt': 'Nítido por dentro desativado',                    'nl': 'Scherpe binnenkant gedeactiveerd',                'fr': "Sharp à l'intérieur désactivé",                   'it': 'Sharp interno disattivato',                       'es': 'Sharp dentro desactivado',                        'pl': 'Ostre wnętrze wyłączone',                         'zh-cn': '锋利的内部已停用'},
    'myalarm adapter settings': {                    'en': 'Adapter settings for myalar',                     'de': 'Adaptereinstellungen für myalarm',                'ru': 'Настройки адаптера для myalarm',                  'pt': 'Configurações do adaptador para myalarm',         'nl': 'Adapterinstellingen voor myalarm',                'fr': "Paramètres d'adaptateur pour myalarm",            'it': "Impostazioni dell'adattatore per myalarm",        'es': 'Ajustes del adaptador para myalarm',              'pl': 'Ustawienia adaptera dla myalarm',                 'zh-cn': 'myalar的适配器设置'},
    'negativ': {                                     'en': 'negate',                                          'de': 'negieren',                                        'ru': 'отрицать',                                        'pt': 'negar',                                           'nl': 'ontkennen',                                       'fr': 'nier',                                            'it': 'negare',                                          'es': 'negar',                                           'pl': 'negować',                                         'zh-cn': '否定'},
    'night_Chips': {                                 'en': 'States for night rest circuit',                   'de': 'Zustände für die Nachtruhe',                      'ru': 'Штаты для ночного отдыха',                        'pt': 'Estados para circuito de descanso noturno',       'nl': 'Staten voor nachtrustcircuit',                    'fr': 'États pour circuit de nuit',                      'it': 'Stati per il circuito di riposo notturno',        'es': 'Estados para el circuito de descanso nocturno.',  'pl': 'Stany na nocny obwód odpoczynku',                 'zh-cn': '国家为夜间休息电路'},
    'night_from': {                                  'en': 'Begins of the night rest',                        'de': 'Beginn der Nachtruhe',                            'ru': 'Начинается ночной отдых',                         'pt': 'Começa do resto da noite',                        'nl': 'Begin van de nachtrust',                          'fr': 'Commence la nuit repos',                          'it': 'Inizia il riposo notturno',                       'es': 'Comienzo del descanso nocturno.',                 'pl': 'Zaczyna się nocny odpoczynek',                    'zh-cn': '开始的夜晚休息'},
    'night_to': {                                    'en': 'Ends of the night rest',                          'de': 'Ende der Nachtruhe',                              'ru': 'Концы ночного отдыха',                            'pt': 'Termina do resto da noite',                       'nl': 'Einde van de nachtrust',                          'fr': 'Fin de la nuit repos',                            'it': 'Fine del riposo notturno',                        'es': 'Finales del descanso nocturno.',                  'pl': 'Koniec nocnego odpoczynku',                       'zh-cn': '晚上休息'},
    'notification': {'en': 'notifications (include night rest)',
        'de': 'Benachrichtigungen (einschließlich Nachtruhe)',
        'ru': 'уведомления (включая ночной отдых)',
        'pt': 'notificações (incluindo descanso noturno)',
        'nl': 'notificaties (inclusief nachtrust)',
        'fr': 'notifications (y compris le repos nocturne)',
        'it': 'notifiche (incluso riposo notturno)',
        'es': 'notificaciones (incluye descanso nocturno)',
        'pl': 'powiadomienia (w tym odpoczynek nocny)',
        'zh-cn': '通知（包括夜间休息）'},
    'notifications': {                               'en': 'Notifications',                                   'de': 'Benachrichtigungen',                              'ru': 'Уведомления',                                     'pt': 'Notificações',                                    'nl': 'Kennisgevingen',                                  'fr': 'Notifications',                                   'it': 'notifiche',                                       'es': 'Notificaciones',                                  'pl': 'Powiadomienia',                                   'zh-cn': '通知事项'},
    'opt_leave': {       'en': 'activation at leaving during countdown',
        'de': 'Aktivierung beim Verlassen während des Countdowns',
        'ru': 'активация при выходе во время обратного отсчета',
        'pt': 'ativação na saída durante a contagem regressiva',
        'nl': 'activering bij vertrek tijdens aftellen',
        'fr': 'activation au départ pendant le compte à rebours',
        'it': "attivazione all'uscita durante il conto alla rovescia",
        'es': 'activación al salir durante la cuenta atrás',
        'pl': 'aktywacja przy wyjściu podczas odliczania',
        'zh-cn': '倒计时离开时激活'                              },
    'opt_siren': { 'en': 'activate outside siren at burgle sharp inside',
        'de': 'Außensirene bei Einbruch scharf innen aktivieren',
        'ru': 'активировать внешнюю сирену при взломе резко внутри',
        'pt': 'ativar a sirene externa em arrombamento afiado por dentro',
        'nl': 'activeer buitensirene bij inbraak scherp binnen',
        'fr': "activer la sirène extérieure en cas d'effraction à l'intérieur",
        'it': "attivare la sirena esterna in caso di scasso acuto all'interno",
        'es': 'activar la sirena exterior en caso de robo agudo en el interior',
        'pl': 'aktywuj syrenę zewnętrzną podczas włamywania się do środka',
        'zh-cn': '内部爆破时激活外部警报器' },
    'opt_log': {                                     'en': 'Log output',                                      'de': 'Ausgabe protokollieren',                          'ru': 'Выход журнала',                                   'pt': 'Saída de log',                                    'nl': 'Log output',                                      'fr': 'Journal de sortie',                               'it': "Registrare l'output",                             'es': 'Salida de registro',                              'pl': 'Wynik dziennika',                                 'zh-cn': '记录输出'},
    'opt_night': {                                   'en': 'Control configured states during night rest',     'de': 'Konfigurierte Zustände während der Nachtruhe überwachen', 'ru': 'Контроль настроенных состояний во время ночного отдыха', 'pt': 'Controle configurado estados durante o resto da noite', 'nl': 'Controleer geconfigureerde staten tijdens nachtrust', 'fr': 'Contrôler les états configurés pendant le repos de nuit', 'it': 'Controllare gli stati configurati durante il riposo notturno', 'es': 'Control de estados configurados durante el descanso nocturno.', 'pl': 'Kontroluj skonfigurowane stany podczas nocnego odpoczynku', 'zh-cn': '在夜间休息期间控制配置状态'},
    'opt_night_silent': {'en': 'no speech output during night rest',
        'de': 'Keine Sprachausgabe während der Nachtruhe',
        'ru': 'нет речи во время ночного отдыха',
        'pt': 'sem saída de voz durante o descanso noturno',
        'nl': 'geen spraakuitvoer tijdens nachtrust',
        'fr': 'pas de sortie vocale pendant le repos nocturne',
        'it': 'nessuna riproduzione vocale durante il riposo notturno',
        'es': 'sin salida de voz durante el descanso nocturno',
        'pl': 'brak mowy podczas nocnego odpoczynku',
        'zh-cn': '夜间休息时无语音输出'},
    'opt_say_changes': {                             'en': 'Changes during night rest',                       'de': 'Änderungen während der Nachtruhe',                'ru': 'Изменения во время ночного отдыха',               'pt': 'Mudanças durante o descanso noturno',             'nl': 'Veranderingen tijdens nachtrust',                 'fr': 'Changements pendant le repos nocturne',           'it': 'Cambiamenti durante il riposo notturno',          'es': 'Cambios durante el descanso nocturno.',           'pl': 'Zmiany podczas nocnego odpoczynku',               'zh-cn': '夜间休息时的变化'},
    'opt_say_names': {                               'en': 'Devices Names output',                            'de': 'Gerätenamen ausgegeben',                          'ru': 'Вывод названий устройств',                        'pt': 'Saída de nomes de dispositivos',                  'nl': 'Uitvoer van apparaatnamen',                       'fr': 'Sortie Noms des appareils',                       'it': 'Output dei nomi dei dispositivi',                 'es': 'Salida de nombres de dispositivos',               'pl': 'Dane wyjściowe nazw urządzeń',                    'zh-cn': '设备名称输出'},
    'opt_say_night': {                               'en': "Warnings at the beginning of the night's rest",   'de': 'Warnungen zu Beginn der Nachtruhe',               'ru': 'Предупреждения в начале ночного отдыха',          'pt': 'Advertências no início do resto da noite',        'nl': 'Waarschuwingen aan het begin van de nachtrust',   'fr': 'Avertissements au début du repos nocturne',       'it': "Avvertenze all'inizio del riposo notturno",       'es': 'Advertencias al comienzo del descanso nocturno.', 'pl': 'Ostrzeżenia na początku nocnego odpoczynku',      'zh-cn': '夜间休息开始时的警告'},
    'opt_say_warn': {                                'en': 'Warnings at the beginning of the warn circuit activate', 'de': 'Warnungen zu Beginn der Warnkreis Aktivierung',   'ru': 'Предупреждения в начале ночного отдыха',          'pt': 'Advertências no início do resto da noite',        'nl': 'Waarschuwingen aan het begin van de nachtrust',   'fr': 'Avertissements au début du repos nocturne',       'it': "Avvertenze all'inizio del riposo notturno",       'es': 'Advertencias al comienzo del descanso nocturno.', 'pl': 'Ostrzeżenia na początku nocnego odpoczynku',      'zh-cn': '夜间休息开始时的警告'},
    'opt_say_warn_changes': {                        'en': 'Changes during sharp inside',                     'de': 'Veränderungen während SCHARF INTERN',             'ru': 'Изменения во время ночного отдыха и резких внутри', 'pt': 'Alterações durante o descanso noturno e nítidas por dentro', 'nl': 'Veranderingen tijdens nachtrust en scherp van binnen', 'fr': 'Changements pendant le repos nocturne et intérieur vif', 'it': "Cambiamenti durante il riposo notturno e taglienti all'interno", 'es': 'Cambios durante el descanso nocturno y agudo por dentro', 'pl': 'Zmiany podczas nocnego odpoczynku i ostre wnętrze', 'zh-cn': '夜间休息时变化多端，内部锐利'},
    'opt_telegram': {'en': 'special parameters for Telegram',
        'de': 'spezielle Parameter für Telegram',
        'ru': 'специальные параметры для Telegram',
        'pt': 'parâmetros especiais para Telegram',
        'nl': 'speciale parameters voor Telegram',
        'fr': 'paramètres spéciaux pour Telegram',
        'it': 'parametri speciali per Telegram',
        'es': 'parámetros especiales para Telegram',
        'pl': 'specjalne parametry dla Telegrama',
        'zh-cn': '电报的特殊参数'},

    'opt_warning': {                                 'en': 'Ignore configured states at activation',          'de': 'Konfigurierte Zustände bei der Aktivierung ignorieren', 'ru': 'Игнорировать настроенные состояния предупреждения при активации', 'pt': 'Ignore os estados de aviso configurados na ativação', 'nl': 'Negeer geconfigureerde waarschuwingsstatussen bij activering', 'fr': "Ignorer les états d'avertissement configurés lors de l'activation", 'it': "Ignora gli stati di avviso configurati all'attivazione", 'es': 'Ignorar los estados de advertencia configurados en la activación', 'pl': 'Zignoruj ​​skonfigurowane stany ostrzeżeń przy aktywacji', 'zh-cn': '激活时忽略已配置的警告状态'},
    'other_alarms': {'en': 'other alarms',
        'de': 'andere Alarme',
        'ru': 'другие будильники',
        'pt': 'outros alarmes',
        'nl': 'andere alarmen',
        'fr': 'autres alarmes',
        'it': 'altri allarmi',
        'es': 'otras alarmas',
        'pl': 'inne alarmy',
        'zh-cn': '其他警报'},
    'output': {                                      'en': 'Output shortcuts',                                'de': 'Ausgabeverknüpfungen',                            'ru': 'Выходные ярлыки',                                 'pt': 'Atalhos de saída',                                'nl': 'Uitvoersnelkoppelingen',                          'fr': 'Raccourcis de sortie',                            'it': 'Scorciatoie di output',                           'es': 'Atajos de salida',                                'pl': 'Skróty wyjściowe',                                'zh-cn': '输出快捷方式'},
    'please': {'en': 'Please, do not use the same states like the main states',
        'de': 'Bitte verwenden Sie nicht dieselben States wie den Haupt-States',
        'ru': 'Пожалуйста, не используйте те же состояния, что и основные состояния.',
        'pt': 'Por favor, não use os mesmos estados que os estados principais',
        'nl': 'Gebruik alsjeblieft niet dezelfde staten als de belangrijkste staten',
        'fr': 'Veuillez ne pas utiliser les mêmes états que les états principaux',
        'it': 'Per favore, non utilizzare gli stessi stati degli stati principali',
        'es': 'Por favor, no use los mismos estados que los estados principales',
        'pl': 'Proszę nie używać tych samych stanów, co główne stany',
        'zh-cn': '请不要使用与主要状态相同的状态'},
    'repeat': {                                      'en': 'repeat',
        'de': 'wiederholen',
        'ru': 'повторение',
        'pt': 'repetir',
        'nl': 'herhaling',
        'fr': 'répéter',
        'it': 'ripetere',
        'es': 'repetir',
        'pl': 'powtarzać',
        'zh-cn': '重复'},
    'sayit': {                                       'en': 'speak output',                                    'de': 'Sprachausgabe',                                   'ru': 'Сайит настройки',                                 'pt': 'Configurações Sayit',                             'nl': 'Sayit-instellingen',                              'fr': 'Paramètres Sayit',                                'it': 'Impostazioni Sayit',                              'es': 'Configuración de Sayit',                          'pl': 'Sayit ustawienia',                                'zh-cn': 'Sayit设置'},
    'sayit_instance': {                              'en': 'Instance',                                        'de': 'Instanz',                                         'ru': 'Саит инстанс',                                    'pt': 'Sayit instance',                                  'nl': 'Sayit-instantie',                                 'fr': 'Instance Sayit',                                  'it': 'Istanza Sayit',                                   'es': 'Instancia de Sayit',                              'pl': 'Sayit instancja',                                 'zh-cn': 'Sayit实例'},
    'second': {                                      'en': 'All time inputs are in second',                   'de': 'Alle Zeiteingaben sind in Sekunden',              'ru': 'Все входы времени в секундах',                    'pt': 'Todas as entradas de tempo estão em segundo',     'nl': 'Alle tijdinvoer staat op de tweede plaats',       'fr': 'Toutes les entrées de temps sont en seconde',     'it': 'Tutti gli input di tempo sono al secondo',        'es': 'Todas las entradas de tiempo están en segundo',   'pl': 'Wszystkie dane wejściowe są w sekundach',         'zh-cn': '所有时间输入均以秒为单位'},
    'sendTo_Chips': {                                'en': 'Notification instnces like Email, Pushover or Telegram', 'de': 'Benachrichtigungsinstanzen wie E-Mail, Pushover oder Telegram', 'ru': 'Уведомления, такие как Email, Pushover или Telegram', 'pt': 'Instâncias de notificação como E-mail, pushover ou telegrama', 'nl': 'Meldingen zoals e-mail, pushover of telegram',    'fr': 'Instance de notification comme Email, Pushover ou Telegram', 'it': 'Le notifiche funzionano come Email, Pushover o Telegram', 'es': 'Instancias de notificación como correo electrónico, pushover o telegrama', 'pl': 'Powiadomienia, takie jak poczta e-mail, pushover lub telegram', 'zh-cn': '通知单，例如电子邮件，Pushover或Telegram'},
    'send_activation': {                             'en': 'Notifications at deactivation and activation',    'de': 'Benachrichtigungen bei Deaktivierung und Aktivierung', 'ru': 'Уведомления при деактивации и активации',         'pt': 'Notificações na desativação e ativação',          'nl': 'Meldingen bij deactivering en activering',        'fr': "Notifications à la désactivation et à l'activation", 'it': 'Notifiche alla disattivazione e attivazione',     'es': 'Notificaciones en la desactivación y activación', 'pl': 'Powiadomienia o dezaktywacji i aktywacji',        'zh-cn': '停用和激活时的通知'},
    'send_alarm': {                                  'en': 'Notifications at burgle',                         'de': 'Benachrichtigungen bei Einbruch',                 'ru': 'Уведомления на Burgle',                           'pt': 'Notificações no burgle',                          'nl': 'Meldingen bij inbraak',                           'fr': 'Notifications à burgle',                          'it': 'Notifiche al burgle',                             'es': 'Notificaciones en burgle',                        'pl': 'Powiadomienia w burgle',                          'zh-cn': '在burgle的通知'},
    'send_alarm_silent': {    'en': 'notification at silent alarm',
        'de': 'Benachrichtigung bei stillem Alarm',
        'ru': 'уведомление при тихой тревоге',
        'pt': 'notificação em alarme silencioso',
        'nl': 'melding bij stil alarm',
        'fr': "notification en cas d'alarme silencieuse",
        'it': "notifica all'allarme silenzioso",
        'es': 'notificación en alarma silenciosa',
        'pl': 'powiadomienie przy cichym alarmie',
        'zh-cn': '静音警报通知'},
    'send_activated_with_warnings': {'en': 'Activated with warnings',
        'de': 'Mit Warnungen aktiviert',
        'ru': 'Активируется с предупреждениями',
        'pt': 'Ativado com avisos',
        'nl': 'Geactiveerd met waarschuwingen',
        'fr': 'Activé avec des avertissements',
        'it': 'Attivato con avvisi',
        'es': 'Activado con advertencias',
        'pl': 'Aktywowany z ostrzeżeniami',
        'zh-cn': '警告激活'},
    'send_activation_warnings': { 'en': 'Notification if warnings upon activation',
        'de': 'Benachrichtigung falls Warnungen bei Aktivierung',
        'ru': 'Уведомление, если предупреждения при активации',
        'pt': 'Notificação se houver avisos na ativação',
        'nl': 'Melding als waarschuwingen bij activering',
        'fr': "Notification si avertissements lors de l'activation",
        'it': "Notifica in caso di avvisi all'attivazione",
        'es': 'Notificación de advertencias sobre la activación',
        'pl': 'Powiadomienie o ostrzeżeniach po aktywacji',
        'zh-cn': '激活时发出警告通知'},
    'send_activation_warnings_night': {'en': 'notification when warnings at beginning night rest',
        'de': 'Benachrichtigung bei Warnungen zu Beginn der Nachtruhe',
        'ru': 'уведомление при предупреждениях о начале ночного отдыха',
        'pt': 'notificação quando avisos no início do descanso noturno',
        'nl': 'melding bij waarschuwingen bij het begin van de nachtrust',
        'fr': 'notification lors des avertissements au début du repos nocturne',
        'it': "notifica quando avvisi all'inizio del riposo notturno",
        'es': 'notificación cuando avisos al inicio del descanso nocturno',
        'pl': 'powiadomienie o ostrzeżeniach na początku odpoczynku nocnego',
        'zh-cn': '在开始夜间休息时发出警告时的通知' },
    'send_failed': {
        'en': 'wrong password',
        'de': 'falsches Passwort',
        'ru': 'неправильный пароль',
        'pt': 'senha incorreta',
        'nl': 'verkeerd wachtwoord',
        'fr': 'mauvais mot de passe',
        'it': 'password errata',
        'es': 'contraseña incorrecta',
        'pl': 'złe hasło',
        'zh-cn': '密码错误'
    },
    'send_notification_changes': {    'en': 'send notifications during sharp, scharp inside and night rest',
        'de': 'Benachrichtigungen während scharf, scharf Innen und Nachtruhe',
        'ru': 'отправлять уведомления во время резкого, резкого внутри и ночью',
        'pt': 'enviar notificações durante agudos, scharp dentro e à noite',
        'nl': 'stuur meldingen tijdens scherp, scherp binnen en nacht',
        'fr': "envoyer des notifications pendant les périodes de pointe, de scharp à l'intérieur et la nuit",
        'it': 'inviare notifiche durante il forte, lo scoppio dentro e la notte',
        'es': 'enviar notificaciones durante la noche aguda, scharp interior y',
        'pl': 'wysyłaj powiadomienia podczas ostrego, ostrego wnętrza i nocy',
        'zh-cn': '在夜间和夜间尖锐地发送通知'},
    'shortcuts': {                                   'en': 'shortcuts',                                       'de': 'Verknüpfungen',                                   'ru': 'сочетания',                                       'pt': 'atalhos',                                         'nl': 'snelkoppelingen',                                 'fr': 'raccourcis',                                      'it': 'scorciatoie',                                     'es': 'atajos',                                          'pl': 'skróty',                                          'zh-cn': '快捷键'},
    'silent_flash': {                                'en': 'flash light frequenz at silent alarm',
        'de': 'Blitzlichtfrequenz bei stillem Alarm',
        'ru': 'Частота вспышки при тихой тревоге',
        'pt': 'luz do flash frequenz em alarme silencioso',
        'nl': 'flitslichtfrequentie bij stil alarm',
        'fr': "fréquence de la lumière flash à l'alarme silencieuse",
        'it': 'luce lampeggiante frequenz a allarme silenzioso',
        'es': 'Frecuencia de luz de flash en alarma silenciosa',
        'pl': 'częstotliwość światła błyskowego przy cichym alarmie',
        'zh-cn': '静音时出现闪光灯频率'},
    'states': {                                      'en': 'monitoring',                                      'de': 'Überwachung',                                     'ru': 'состояния',                                       'pt': 'Estados',                                         'nl': 'Staten',                                          'fr': 'États',                                           'it': 'stati',                                           'es': 'Estados',                                         'pl': 'Stany Zjednoczone',                               'zh-cn': '状态'},
    'text_activated': {                              'en': 'Phrase after activation',                         'de': 'Satz nach Aktivierung',                           'ru': 'Фраза после активации',                           'pt': 'Frase após ativação',                             'nl': 'Zin na activering',                               'fr': 'Phrase après activation',                         'it': "Frase dopo l'attivazione",                        'es': 'Frase después de la activación',                  'pl': 'Zdanie po aktywacji',                             'zh-cn': '激活后的短语'},
    'text_alarm': {                                  'en': 'Phrase at burgle',                                'de': 'Satz bei Einbruch',                               'ru': 'Фраза в бургле',                                  'pt': 'Frase no burgle',                                 'nl': 'Zin in inbraak',                                  'fr': 'Phrase à burgle',                                 'it': 'Frase al burgle',                                 'es': 'Frase en Burgle',                                 'pl': 'Zdanie w burgle',                                 'zh-cn': '在burgle的短语'},
    'text_alarm_pause': {                            'en': 'Sec between Msg',                                 'de': 'Sek zw. Nachr.'                              },
    'text_changes': {                                'en': 'Phrase at changes sharp inside',                  'de': 'Satz Veränderungen während SCHARF INTERN',        'ru': 'Фраза ночью меняется',                            'pt': 'Frase no resto da noite muda',                    'nl': 'Zin in nachtrust verandert',                      'fr': 'Phrase au changement de repos nocturne',          'it': 'La frase durante il riposo notturno cambia',      'es': 'Frase en los cambios de descanso nocturno',       'pl': 'Zwrot w nocnym odpoczynku zmienia się',           'zh-cn': '夜间休息时的短语变化'},
    'text_changes_night': {                          'en': 'Phrase at changes during night rest',             'de': 'Satz bei Änderungen während der Nachtruhe',       'ru': 'Фраза при переменах во время ночного отдыха',     'pt': 'Frase com alterações durante o descanso noturno', 'nl': 'Zin bij veranderingen tijdens nachtrust',         'fr': 'Phrase aux changements pendant le repos nocturne', 'it': 'Frase ai cambiamenti durante il riposo notturno', 'es': 'Frase en los cambios durante el descanso nocturno', 'pl': 'Zwroty przy zmianach podczas nocnego odpoczynku', 'zh-cn': '夜间休息时的变化短语'},
    'text_countdown': {                          'en': 'Time to activation',
        'de': 'Zeit bis zur Aktivierung',
        'ru': 'Время на активацию',
        'pt': 'Hora da ativação',
        'nl': 'Tijd tot activering',
        'fr': "Temps d'activation",
        'it': 'Tempo di attivazione',
        'es': 'Tiempo de activación',
        'pl': 'Czas na aktywację',
        'zh-cn': '激活时间'},
    'text_deactivated': {                            'en': 'Phrase after deactivation',                       'de': 'Satz nach Deaktivierung',                         'ru': 'Фраза после деактивации',                         'pt': 'Frase após desativação',                          'nl': 'Zin na deactivering',                             'fr': 'Phrase après la désactivation',                   'it': 'Frase dopo la disattivazione',                    'es': 'Frase después de la desactivación',               'pl': 'Zdanie po dezaktywacji',                          'zh-cn': '停用后的短语'},
    'text_failed': {                                 'en': 'Phrase at failure',                               'de': 'Satz beim Fehlschlagen der Aktivierung',          'ru': 'Фраза при неудаче',                               'pt': 'Frase ao fracasso',                               'nl': 'Zin bij falen',                                   'fr': "Phrase à l'échec",                                'it': 'Frase al fallimento',                             'es': 'Frase en el fracaso',                             'pl': 'Fraza przy awarii',                               'zh-cn': '失败的短语'},
    'text_nightrest_beginn': {                       'en': 'Phrase night rest begins',                        'de': 'Satz Nachtruhe beginnt',                          'ru': 'Фраза ночного отдыха начинается',                 'pt': 'O resto da noite da frase começa',                'nl': 'Zin nachtrust begint',                            'fr': 'Phrase: le repos nocturne commence',              'it': 'Inizia il riposo notturno di frase',              'es': 'Frase comienza el descanso nocturno',             'pl': 'Rozpoczyna się fraza nocny odpoczynek',           'zh-cn': '短语夜间休息开始'},
    'text_nightrest_end': {                          'en': 'Phrase night rest ends',                          'de': 'Satz Nachtruhe endet',                            'ru': 'Фраза ночного отдыха заканчивается',              'pt': 'Frase de descanso noturno termina',               'nl': 'Zin nachtrust eindigt',                           'fr': 'Expression du repos nocturne',                    'it': 'Il riposo notturno di frase termina',             'es': 'Frase finaliza el descanso nocturno',             'pl': 'Koniec fraz nocnego odpoczynku',                  'zh-cn': '短语夜间休息结束'},
    'text_one': {                                    'en': 'Phrase for additional alart type one (Fire)',     'de': 'Satz nach Meldung Alarmtyp 1 (Feuer)'},
    'text_two': {                                    'en': 'Phrase for additional alart type two (Water)',    'de': 'Satz nach Meldung Alarmtyp 2 (Wasser)'},
    'text_warn_begin': {                             'en': 'Phrase after sharp inside activation',            'de': 'Satz nach scharf innen Aktivierung',              'ru': 'Фраза после резкой внутренней активации',         'pt': 'Frase após ativação interna acentuada',           'nl': 'Zin na scherpe activering van binnen',            'fr': 'Phrase après une forte activation interne',       'it': 'Frase dopo forte attivazione interna',            'es': 'Frase después de una aguda activación interna',   'pl': 'Fraza po ostrej aktywacji wewnętrznej',           'zh-cn': '内部尖锐激活后的短语'},
    'text_warn_end': {                               'en': 'Phrase after sharp inside deactivation',          'de': 'Satz nach scharf innen Deaktivierung',            'ru': 'Фраза после резкой внутренней дезактивации',      'pt': 'Frase após desativação interna acentuada',        'nl': 'Zin na scherpe uitschakeling binnenin',           'fr': "Phrase après une désactivation nette à l'intérieur", 'it': 'Frase dopo marcata disattivazione interna',       'es': 'Frase después de una aguda desactivación interna', 'pl': 'Zwrot po ostrej dezaktywacji wewnętrznej',        'zh-cn': '内部急剧钝化后的短语'},
    'text_warning': {                                'en': 'Phrase of warnings at the beginning night rest and sharp inside', 'de': 'Satz Warnungen beim Beginn der Nachtruhe und SCHARF INTERN', 'ru': 'Фраза в предупреждениях',                         'pt': 'Frase em avisos',                                 'nl': 'Zin bij waarschuwingen',                          'fr': 'Phrase aux avertissements',                       'it': 'Frase agli avvertimenti',                         'es': 'Frase en las advertencias',                       'pl': 'Fraza na ostrzeżenia',                            'zh-cn': '警告短语'},
    'time_activate': {                               'en': 'Activation time',                                 'de': 'Aktivierungszeit',                                'ru': 'Время активации',                                 'pt': 'Tempo de ativação',                               'nl': 'Activeringstijd',                                 'fr': "Temps d'activation",                              'it': 'Tempo di attivazione',                            'es': 'Tiempo de activacion',                            'pl': 'Czas aktywacji',                                  'zh-cn': '激活时间（秒）'},
    'time_alarm': {                                  'en': 'Siren time at burgle',                            'de': 'Sirenenzeit bei Einbruch',                        'ru': 'Сирена время в Burgle',                           'pt': 'Hora da sirene no burgle',                        'nl': 'Sirenetijd bij inbraak',                          'fr': 'Temps de sirène à burgle',                        'it': 'Ora della sirena al burgle',                      'es': 'Tiempo de sirena en burgle',                      'pl': 'Czas syreny w burgle',                            'zh-cn': '警报器的警笛时间在几秒钟内'},
    'time_silent': {                                 'en': 'Alarm delay',                                     'de': 'Alarmverzögerung',                                'ru': 'Задержка тревоги в секундах',                     'pt': 'Atraso do alarme em segundos',                    'nl': 'Alarmvertraging in seconden',                     'fr': "Délai d'alarme en secondes",                      'it': "Ritardo dell'allarme in secondi",                 'es': 'Retraso de alarma en segundos',                   'pl': 'Opóźnienie alarmu w sekundach',                   'zh-cn': '警报延迟秒数'},
    'time_silent_inside': { 'en': 'alarm delay sharp inside',
        'de': 'Alarmverzögerung scharf innen',
        'ru': 'задержка будильника резко внутри',
        'pt': 'atraso de alarme acentuado por dentro',
        'nl': 'alarmvertraging scherp van binnen',
        'fr': "retard d'alarme net à l'intérieur",
        'it': "ritardo di allarme acuto all'interno",
        'es': 'retardo de alarma agudo en el interior',
        'pl': 'opóźnienie alarmu ostre wewnątrz',
        'zh-cn': '内部报警延迟尖锐'},
    'time_warning': {                                'en': 'Siren time at sharp inside',
        'de': 'Sirenenzeit scharf innen',
        'ru': 'Время сирены на резком внутри',
        'pt': 'Tempo da sirene no interior afiado',
        'nl': 'Sirenetijd binnen scherp',
        'fr': "Heure de la sirène à l'intérieur pointu",
        'it': 'Tempo di sirena al suo interno acuto',
        'es': 'Tiempo de sirena en el interior agudo',
        'pl': 'Czas syreny ostry w środku',
        'zh-cn': '警笛声时间在里面'},
    'trigger_values': {                              'en': 'Trigger value',                                   'de': 'Auslösewert',                                     'ru': 'Значение триггера',                               'pt': 'Valor do gatilho',                                'nl': 'Triggerwaarde',                                   'fr': 'Valeur de déclenchement',                         'it': 'Valore di trigger',                               'es': 'Valor de activación',                             'pl': 'Wartość wyzwalacza',                              'zh-cn': '触发值'},
    'values': {                                      'en': 'set values',                                      'de': 'Setzwerte',                                       'ru': 'установить значения',                             'pt': 'definir valores',                                 'nl': 'waarden instellen',                               'fr': 'définir des valeurs',                             'it': 'impostare valori',                                'es': 'establecer valores',                              'pl': 'ustawić wartości',                                'zh-cn': '设定值'},
    'warning_Chips': {                               'en': 'States for warning circuit',                      'de': 'Zustände für den Warnkreis',                      'ru': 'Состояния для предупреждения цепи',               'pt': 'Estados para circuito de aviso',                  'nl': 'Staten voor waarschuwingscircuit',                'fr': "États pour le circuit d'avertissement",           'it': 'Stati per circuito di allarme',                   'es': 'Estados para circuito de advertencia',            'pl': 'Stany do obwodu ostrzegawczego',                  'zh-cn': '国家警告电路'},
    'words': {                                       'en': 'Words',                                           'de': 'Texte',                                           'ru': 'слова',                                           'pt': 'Palavras',                                        'nl': 'Woorden',                                         'fr': 'Mots',                                            'it': 'Parole',                                          'es': 'Palabras',                                        'pl': 'Słowa',                                           'zh-cn': '话'},
    'zones': {        'en': 'zones',
        'de': 'Zonen',
        'ru': 'зоны',
        'pt': 'zonas',
        'nl': 'zones',
        'fr': 'zones',
        'it': 'zone',
        'es': 'zonas',
        'pl': 'strefy',
        'zh-cn': '区域'                               },
};
